// Auto-generated by scripts/generate-models.js
// Do not edit manually — run `npm run generate:models` to update.

//   Дата и время в UTC
export type UtcDateTime = string;

//   UUID идентификатор
export type uuid = string;

/** Бронирование, созданное гостем на выбранный слот */
export interface Booking {
  id: string;
  eventTypeId: string;
  guestName: string;
  guestEmail: string;
  startTime: string;
  endTime: string;
  createdAt: string;
}

/** Бронирование пересекается с существующим */
export interface ConflictError {
  code: 'CONFLICT';
  message: string;
}

/** Запрос на создание бронирования */
export interface CreateBookingRequest {
  eventTypeId: string;
  guestName: string;
  guestEmail: string;
  startTime: string;
}

/** Запрос на создание типа события */
export interface CreateEventTypeRequest {
  title: string;
  description: string;
  duration: number;
}

/** Тип события, создаваемый владельцем календаря */
export interface EventType {
  id: string;
  title: string;
  description: string;
  duration: number;
}

/** Ресурс не найден */
export interface NotFoundError {
  code: 'NOT_FOUND';
  message: string;
}

/** Свободный временной слот */
export interface Slot {
  startTime: string;
  endTime: string;
}

/** Запрос на обновление типа события */
export interface UpdateEventTypeRequest {
  title?: string;
  description?: string;
  duration?: number;
}

/** Ошибка валидации входных данных */
export interface ValidationError {
  code: 'VALIDATION_ERROR';
  message: string;
  details: string[];
}
