const fs = require('node:fs');
const path = require('node:path');
const { parse } = require('yaml');

const OPENAPI_PATH = path.resolve(__dirname, '../specs/generated/@typespec/openapi3/openapi.yaml');
const OUTPUT_PATH = path.resolve(__dirname, '../frontend/src/app/models/api.types.ts');

const TYPE_MAP = {
  string: 'string',
  integer: 'number',
  number: 'number',
  boolean: 'boolean',
};

function resolveTypeName(ref) {
  return ref.replace('#/components/schemas/', '');
}

function mapType(schema, schemas) {
  if (schema.$ref) {
    const name = resolveTypeName(schema.$ref);
    if (name === 'uuid' || name === 'UtcDateTime') {
      return 'string';
    }
    return name;
  }

  if (schema.type === 'array' && schema.items) {
    const itemType = mapType(schema.items, schemas);
    return `${itemType}[]`;
  }

  if (schema.enum) {
    return schema.enum.map((v) => `'${v}'`).join(' | ');
  }

  return TYPE_MAP[schema.type] || 'unknown';
}

function generate() {
  const raw = fs.readFileSync(OPENAPI_PATH, 'utf-8');
  const doc = parse(raw);
  const schemas = doc.components?.schemas || {};

  const skipScalars = ['uuid', 'UtcDateTime'];
  const lines = [];
  const scalarLines = [];

  for (const [name, schema] of Object.entries(schemas)) {
    if (skipScalars.includes(name)) {
      const desc = schema.description ? `  ${schema.description}` : '';
      scalarLines.push(`// ${desc}`);
      scalarLines.push(`export type ${name} = string;\n`);
      continue;
    }

    if (schema.type !== 'object') continue;

    if (schema.description) {
      lines.push(`/** ${schema.description} */`);
    }

    lines.push(`export interface ${name} {`);

    const required = new Set(schema.required || []);

    for (const [propName, propSchema] of Object.entries(schema.properties)) {
      const isRequired = required.has(propName);
      const tsType = mapType(propSchema, schemas);
      const optional = isRequired ? '' : '?';

      if (propSchema.description) {
        lines.push(`  /** ${propSchema.description} */`);
      }

      lines.push(`  ${propName}${optional}: ${tsType};`);
    }

    lines.push('}\n');
  }

  const output = [
    '// Auto-generated by scripts/generate-models.js',
    '// Do not edit manually — run `npm run generate:models` to update.',
    '',
    ...scalarLines,
    ...lines,
  ].join('\n');

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');

  console.log(`✓ Generated models → ${OUTPUT_PATH}`);
}

generate();
